/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PatientRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HealthFacility.PatientOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthFacilityManager.SendBillToPatient;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhang
 */
public class ViewBillingJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private UserAccount userAccount;
    private PatientOrganization organization;
    private Enterprise enterprise;
    
    private Patient patient;
    /**
     * Creates new form ViewBillingJPanel
     */
    public ViewBillingJPanel(JPanel userProcessContainer, UserAccount userAccount, Patient patient, PatientOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.patient=patient;
      
        this.userAccount = userAccount;
        
        populateData();
    }

      public void populateData() {
        jLabel5.setText(userAccount.getEmployee().getName());
        jLabel6.setText(userAccount.getUsername());
        
        
        
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnViw = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setText("The Health Billing");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 63, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 199, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Patient UserAccount :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 402, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 199, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 402, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setText("Billing :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 799, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 744, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 1044, -1, -1));

        btnViw.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnViw.setText("View My Billing");
        btnViw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViwActionPerformed(evt);
            }
        });
        add(btnViw, new org.netbeans.lib.awtextra.AbsoluteConstraints(973, 1044, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel10.setText("$");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(995, 778, -1, -1));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 744, 222, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 775, 220, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViwActionPerformed
        // TODO add your handling code here:
        double bill=0;
        for (WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof SendBillToPatient) {
                
                 bill = ((SendBillToPatient) wr).getBill();
                if (bill == 0) {
                    JOptionPane.showMessageDialog(null, "Bill not generated yet!");
                } else {
                   
                    jLabel12.setText(String.valueOf(bill));
                      System.out.println("Your Health Billing amount is " +bill);
                }
            }
        }
        
    }//GEN-LAST:event_btnViwActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
