/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ScientistRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthFacility.DoctorOrganization;
import Business.Organization.Organization;
import Business.Patient.Disease;
import Business.Patient.Gene;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientRequest.RequestToDoctor;
import Business.WorkQueue.ScientistRole.RequestToHealthDate;
import Interface.PatientRole.PatientWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhang
 */
public class SendRequestToDoctorJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Ecosystem business;
    private Network n;
    /**
     * Creates new form SendRequestToDoctorJPanel
     */
    public SendRequestToDoctorJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,Ecosystem business) {
        initComponents();
        
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business=business;
        n=new Network();
        jLabel2.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        diseaseJTextField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        geneJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Enterprise :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 277, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("<Value>");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 277, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Disease :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 448, -1, -1));

        diseaseJTextField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(diseaseJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 445, 670, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 967, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 967, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("Gene :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 618, -1, -1));

        geneJTextField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(geneJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 618, 670, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("Message :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 785, -1, -1));

        messageJTextField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        messageJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageJTextFieldActionPerformed(evt);
            }
        });
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 782, 673, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
         // TODO add your handling code here:
         String message = diseaseJTextField.getText();
         String gene =geneJTextField.getText();
         
         
         Disease disease=new Disease();
         Gene g=new Gene();
         
         disease.setName(message);
         g.setName(gene);
         
        RequestToHealthDate request = new RequestToHealthDate();
        
        request.setDisease(disease);
        request.setGene(g);
        request.setMessage(messageJTextField.getText());
        request.setSender(userAccount);
        request.setStatus("Sent");
        
        
        Organization org = null;
        
        for (Network n : business.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organiz : e.getOrganizationDirectory().getOrganizationList()) {
                    if (organiz instanceof DoctorOrganization) {
                        org = organiz;
                        org.getWorkQueue().getWorkRequestList().add(request);
                        JOptionPane.showMessageDialog(null, "Request For Health Date");
                    }
                }
            }
        
        }     
        
         userAccount.getWorkQueue().getWorkRequestList().add(request);
         
     /*for (Network network :business.getNetworkList()) {
            if (network.equals(n)) {
       for (Enterprise enterprise :network.getEnterpriseDirectory().getEnterpriseList()) {
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DoctorOrganization){
                org = organization;
                break;
            }
          }
       }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        
        
        JOptionPane.showMessageDialog(null, "Has Send To Doctor Organization");
        }*/
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
           userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ScientistWorkAreaJPanel dwjp = (ScientistWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void messageJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField diseaseJTextField;
    private javax.swing.JTextField geneJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField messageJTextField;
    // End of variables declaration//GEN-END:variables
}
