/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Organization.HealthFacility.PatientOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientRequest.RequestToDoctor;
import Business.WorkQueue.WorkRequest;
import Interface.HealthFacilityManagerRole.BillingJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhang
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PatientOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Patient patient;
    /**
     * Creates new form RequestDoctorJPanel
     */
    public PatientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Patient patient,PatientOrganization organization, Enterprise enterprise) {
        initComponents();
        
         this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patient=patient;
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
    }
    
     public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) requestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if (request instanceof RequestToDoctor) {
            Object[] row = new Object[6];
            row[0] = request.getMessage();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            
            
            row[3]=((RequestToDoctor)request).getDisease();
            row[4]=((RequestToDoctor)request).getDrug();
            row[5]=((RequestToDoctor) request).getPrice();
           
            
            
            
            model.addRow(row);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Enterprise :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 297, -1, -1));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        valueLabel.setText("<Value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 297, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel3.setText("Patient Work Area");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 128, -1, -1));

        requestJTable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Receiver", "Status", "Disease", "Drug", "Price"
            }
        ));
        requestJTable.setRowHeight(30);
        jScrollPane1.setViewportView(requestJTable);
        if (requestJTable.getColumnModel().getColumnCount() > 0) {
            requestJTable.getColumnModel().getColumn(2).setResizable(false);
            requestJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 430, 1510, 201));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton1.setText("Refresh Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1131, 293, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton2.setText("Send Request To Doctor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 670, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton3.setText("View My Billing");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 990, 540, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestServiceJPanel", new RequestServiceJPanel(userProcessContainer, userAccount, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         populateRequestTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         ViewBillingJPanel  sendRequestToDrugManufactoryJPanel =new    ViewBillingJPanel( userProcessContainer, userAccount, patient,organization, enterprise);
       userProcessContainer.add(" sendRequestToDrugManufactoryJPanel",  sendRequestToDrugManufactoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requestJTable;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
