/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.HealthFacilityManagerRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HealthFacility.HealthFacilityManagerOrganization;
import Business.Organization.HealthFacility.PatientOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Role.PatientRole.PatientRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.Verify.StringVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhang
 */
public class AddPatientJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private HealthFacilityManagerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Ecosystem busines;
    private Patient patient;
    private Boolean checkAddress;
    private UserAccount consumerUserAccount;
    /**
     * Creates new form AddPatientJPanel
     */
    public AddPatientJPanel(JPanel userProcessContainer, UserAccount account, HealthFacilityManagerOrganization organization, Enterprise enterprise, Ecosystem busines, Patient patient) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.busines = busines;
        this.patient=patient;
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnSet = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setText("Add Patient To The System");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 113, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 384, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("User Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("Password :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 381, 597, -1));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 597, -1));

        btnSet.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnSet.setText("Set User Account");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });
        add(btnSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(993, 1051, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1051, -1, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 597, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("Address :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 780, 270, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 790, 590, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        // TODO add your handling code here:
        StringVerifier stringVerify = new StringVerifier();
        Role r = new PatientRole();
        if (stringVerify.verify(txtName) && stringVerify.verify(txtUserName) && stringVerify.verify(jTextField1));
        {
            String name = txtName.getText();
            
            String userName = txtUserName.getText();

            char[] passwordCharArray = txtPassword.getPassword();
            String password = String.valueOf(passwordCharArray);
            
            patient.setAddress(jTextField1.getText());
            patient.setName(name);

            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof PatientOrganization) {
                    if (busines.checkIfUsernameIsUnique(userName)) {
                        
                        Patient employee = org.getEmployeeDirectory().createPatient(name);
                        UserAccount consumerUserAccount = org.getUserAccountDirectory().createUserAccount(userName, password, employee, r);

                        JOptionPane.showMessageDialog(null, "User account created");
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null, "Cannot have  User Name match");
                        break;
                    }
                }
            }
            //Creating a new role For Consumer
        }
    }//GEN-LAST:event_btnSetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePatientJPanel dwjp = (ManagePatientJPanel) component;
        dwjp.populateTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
