/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.HealthFacilityManagerRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HealthFacility.PatientOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthFacilityManager.SendBillToPatient;
import Business.WorkQueue.PatientRequest.RequestToDoctor;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhang
 */
public class BillingJPanel extends javax.swing.JPanel {

     JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    Ecosystem business;
    double amount;
    
    /**
     * Creates new form BillingJPanel
     */
    public BillingJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        amount = 0.0;
        populateComboBox();
    }

     public void populateComboBox() {
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof PatientOrganization) {
                for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                    jComboBox1.addItem(ua);

                }
            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnview = new javax.swing.JButton();
        btnsend = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setText("Send Billing To Patients");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 128, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Patient UserAccount ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 298, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 292, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Charge Applied :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 576, -1, -1));

        btnview.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnview.setText("View The Charges");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 791, 435, -1));

        btnsend.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnsend.setText("Send Bill To Patient");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        add(btnsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 968, -1, -1));

        btnback.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 957, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("0.0");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 576, 199, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("$");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1085, 576, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        List<RequestToDoctor> list=new ArrayList<>();
        
        UserAccount ua = (UserAccount) jComboBox1.getSelectedItem();
        for (WorkRequest request :ua.getWorkQueue().getWorkRequestList()) {
            if (request instanceof RequestToDoctor &&  ua.getWorkQueue().getWorkRequestList().contains(request)) {
                list.add((RequestToDoctor) request);
            }
        }
        
        for (int i=0;i<list.size();i++) {
            amount=amount+list.get(i).getPrice();
        }
        
        jLabel4.setText(Double.toString(amount));
        
    }//GEN-LAST:event_btnviewActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        
        UserAccount ua = (UserAccount) jComboBox1.getSelectedItem();
        if (amount != 0.0) {
            SendBillToPatient request = new  SendBillToPatient();
            request.setBill(amount);
            
            ua.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "The Patient bill is sent");
        } else {
            JOptionPane.showMessageDialog(null, "You cannot charge 0 bill amount Patient");
        }
    }//GEN-LAST:event_btnsendActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnview;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
