/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdministrativeRole.HealthFacility;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Interface.AdministrativeRole.Manufactory.ManufactoryManageEmployeeJPanel;
import Interface.AdministrativeRole.Manufactory.ManufactoryManageOrganizationJPanel;
import Interface.AdministrativeRole.Manufactory.ManufactoryManageUserJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author zhang
 */
public class HealthFacilityAdminWorkAreaJPanel extends javax.swing.JPanel {
     JPanel userProcessContainer;
    Enterprise enterprise;
    Ecosystem business;
    /**
    /**
     * Creates new form FacilityAdminWorkAreaJPanel
     */
    public HealthFacilityAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnmanageOrganization = new javax.swing.JButton();
        btnManageEmployee = new javax.swing.JButton();
        btnManageUser = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setText("           Facility Admin Work Area");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 127, 1061, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        jPanel1.add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 318, -1, -1));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        valueLabel.setText("<Value>");
        jPanel1.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 318, -1, -1));

        btnmanageOrganization.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnmanageOrganization.setText("Manage Organization");
        btnmanageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageOrganizationActionPerformed(evt);
            }
        });
        jPanel1.add(btnmanageOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 497, -1, -1));

        btnManageEmployee.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnManageEmployee.setText("Manage Employee");
        btnManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 648, 481, -1));

        btnManageUser.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnManageUser.setText("Manage Users");
        btnManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 823, 481, -1));

        btnDashboard.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 994, 481, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(380, 380, 380))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageOrganizationActionPerformed
        // TODO add your handling code here:
        HealthFacilityManageOrganizationJPanel manageOrganizationJPanel = new HealthFacilityManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmanageOrganizationActionPerformed

    private void btnManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeeActionPerformed
        // TODO add your handling code here:
         HealthFacilityManageEmployeeJPanel manageEmployeeJPanel = new HealthFacilityManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEmployeeActionPerformed

    private void btnManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserActionPerformed
        // TODO add your handling code here:
         FacilityManageUserJPanel muajp = new FacilityManageUserJPanel(userProcessContainer, enterprise,business);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageUserActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        
        DashboardForHealthFacilityJPanel muajp = new  DashboardForHealthFacilityJPanel(userProcessContainer, enterprise,business);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnManageEmployee;
    private javax.swing.JButton btnManageUser;
    private javax.swing.JButton btnmanageOrganization;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
