/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CompoundManufactoryRole;

import Business.Compound.Compound;
import Business.Drug.Drug;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhang
 */
public class ViewCompoundJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
     private Compound compound;
    
    /**
     * Creates new form ViewCompoundJPanel
     */
    public ViewCompoundJPanel(JPanel userProcessContainer, Compound compound) {
        initComponents();
        
         this.userProcessContainer=userProcessContainer;
         this.compound=compound;
         populateAccountDetails();
         
         btnSave.setEnabled(false);
         btnUpdate.setEnabled(true);
   
    
    }
    
    
     private void populateAccountDetails() {
        nameJTextField.setText(compound.getName());
        idJTextField.setText(String.valueOf(compound.getNum()));
        descriptionJTextField.setText(compound.getDescription());
        formulaJTextField.setText(compound.getMolecularFormula());
        structureJTextField.setText(compound.getMolecularStructure());
        
        
        
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        idJTextField = new javax.swing.JTextField();
        descriptionJTextField = new javax.swing.JTextField();
        formulaJTextField = new javax.swing.JTextField();
        structureJTextField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setText("View Compound");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Compound Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 323, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("  Compound ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 453, 380, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("   Description :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 593, 350, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("MolecularFormula :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 753, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setText("MolecularStructure :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 903, -1, -1));

        nameJTextField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 313, 570, -1));

        idJTextField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        idJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idJTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 570, -1));

        descriptionJTextField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        descriptionJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionJTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(descriptionJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 615, 570, -1));

        formulaJTextField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        formulaJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulaJTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(formulaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 774, 580, -1));

        structureJTextField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        structureJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                structureJTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(structureJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 920, 590, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1060, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 1070, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1060, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7.setText("Enterprise :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setText("<Value>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 141, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1600, 1190));
    }// </editor-fold>//GEN-END:initComponents

    private void idJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idJTextFieldActionPerformed

    private void descriptionJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionJTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_descriptionJTextFieldActionPerformed

    private void formulaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formulaJTextFieldActionPerformed

    private void structureJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_structureJTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_structureJTextFieldActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CompoundManufactoryJPanel p = (CompoundManufactoryJPanel) component;
        p.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         nameJTextField.setEnabled(true);
         idJTextField.setEnabled(true);
          descriptionJTextField.setEnabled(true);
          formulaJTextField.setEnabled(true);
          structureJTextField.setEnabled(true);
         
          
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
      compound.setName(nameJTextField.getText());
        compound.setNum(Integer.parseInt(idJTextField.getText()));
        compound.setDescription(descriptionJTextField.getText());
        compound.setMolecularFormula(formulaJTextField.getText());
        compound.setMolecularStructure(structureJTextField.getText());
        
         nameJTextField.setEnabled(false);
         idJTextField.setEnabled(false);
          descriptionJTextField.setEnabled(false);
           formulaJTextField.setEnabled(false);
           structureJTextField.setEnabled(false);
           
        
          
          btnSave.setEnabled(false);
          btnUpdate.setEnabled(true);
        
        JOptionPane.showMessageDialog(null,"Compound  Updataed Successfully");
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField descriptionJTextField;
    private javax.swing.JTextField formulaJTextField;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField structureJTextField;
    // End of variables declaration//GEN-END:variables
}
