/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DrugManufactoryRole;

import Business.WorkQueue.HealthFacilityManager.RequestToDrugManufactoryForMoreDrug;
import Business.WorkQueue.ScientistRole.SendResultToDrugManufactory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author zhang
 */
public class ViewTheResultJPanel extends javax.swing.JPanel {

     JPanel userProcessContainer;
      SendResultToDrugManufactory request;
    /**
     * Creates new form ViewTheResultJPanel
     */
    public ViewTheResultJPanel( JPanel userProcessContainer, SendResultToDrugManufactory request) {
        initComponents();
             this.userProcessContainer = userProcessContainer;
        this.request = request;
        
        txtTopic.setText(request.getMessage());
        txtDescription.setText(request.getDescription());
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTopic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setText("The New Reseach Result");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 118, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Research Result :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        txtTopic.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(txtTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 881, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Description :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 878, 389));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 1013, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    
     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtTopic;
    // End of variables declaration//GEN-END:variables
}
