/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.HealthFacilityManagerRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ClinicalTrial.ScientistOrganization;
import Business.Organization.HealthFacility.HealthFacilityManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthFacilityManager.RequestToDrugManufactoryForMoreDrug;
import Business.WorkQueue.ScientistRole.RequestToHealthDate;
import Business.WorkQueue.WorkRequest;
import Interface.ScientistRole.SendRequestToDoctorJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhang
 */
public class SendRequestToDrugManufactoryJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private HealthFacilityManagerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private Ecosystem business;
    /**
     * Creates new form SendRequestToDrugManufactoryJPanel
     */
    public SendRequestToDrugManufactoryJPanel(JPanel userProcessContainer, UserAccount account, HealthFacilityManagerOrganization organization, Enterprise enterprise,Ecosystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business=business;
        valueJLabel.setText(enterprise.getName());
        populateRequestTable();
    }
    
     public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if (request instanceof RequestToDrugManufactoryForMoreDrug) {
            Object[] row = new Object[6];
            row[0] = ((RequestToDrugManufactoryForMoreDrug) request).getDrug();
            row[1]= ((RequestToDrugManufactoryForMoreDrug)request).getDrugNum();
            row[2]=request;
            
            row[3] = request.getStatus();
            
            row[4]=request.getReceiver();
            row[5]=((RequestToDrugManufactoryForMoreDrug) request).getResult();
            
           /* String result = ((RequestToDoctor) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;*/
            
            
            
            model.addRow(row);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valueJLabel = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSend = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setText("Send Request To Drug Manufactory ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 54, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel2.setText("For More Drug");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 154, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Enterprise : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 300, -1, -1));

        valueJLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        valueJLabel.setText("<Value>");
        add(valueJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 300, -1, -1));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnRefresh.setText("Refresh Table");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 306, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Number", "Message", "Status", "Receiver", "Result"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 411, 1359, -1));

        btnSend.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnSend.setText("Send Request To Doctor Manufactory");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 1011, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 1011, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateRequestTable(); 
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestMoreDrugJPanel", new RequestMoreDrugJPanel(userProcessContainer, userAccount, enterprise,business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel valueJLabel;
    // End of variables declaration//GEN-END:variables
}
