/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CompoundManufactoryRole;

import Business.Compound.Compound;
import Business.Compound.CompoundHistory;
import Business.Drug.Drug;
import Business.Drug.DrugHistory;
import Business.Enterprise.Enterprise;
import Business.Organization.Manufactory.CompoundManufactoryOrganization;
import Business.Organization.Manufactory.DrugManufactoryOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DrugManufactory.SendRequestToCompoundManufactory;
import Business.WorkQueue.PatientRequest.RequestToDoctor;
import Business.WorkQueue.WorkRequest;
import Interface.DoctorRole.ProcessRequestJPanel;
import Interface.DrugManufactoryRole.CreateDrugJPanel;
import Interface.DrugManufactoryRole.ViewDrugJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhang
 */
public class CompoundManufactoryJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private CompoundManufactoryOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private CompoundHistory compoundHistory;
    /**
     * Creates new form CompoundManufactoryJPanel
     */
    public CompoundManufactoryJPanel(JPanel userProcessContainer, UserAccount account, CompoundManufactoryOrganization organization, Enterprise enterprise) {
        initComponents();
        
          this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        jLabel1.setText(enterprise.getName());
        
        compoundHistory=new CompoundHistory();
        
        populateTable();
        populateTable2();
    }

    public CompoundHistory getCompoundHistory() {
        return compoundHistory;
    }

    
    
    
     public void populateTable() {
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        for (Compound c:compoundHistory.getCompoundHistory()) {
            Object[] row=new Object[3];
            
            row[0]=c;
            row[1]=c.getNum();
            row[2]=c.getDescription();
            
            
            dtm.addRow(row);
        }
    }

     public void populateTable2() {
          DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
          if (request instanceof SendRequestToCompoundManufactory) {
            Object[] row = new Object[7];
            row[0] = ((SendRequestToCompoundManufactory) request).getCompound();
            row[1] = ((SendRequestToCompoundManufactory) request).getCompoundNum();
            row[2] = request;
            row[3] = request.getStatus();
            row[4]=request.getSender();
            row[5]=request.getReceiver();
            row[6]=((SendRequestToCompoundManufactory) request).getResult();
            
            model.addRow(row);
          }
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setText("Compound Manufactory ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 38, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("<Value>");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compound", "CompoundID", "Description"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 237, 1320, 217));

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        btnView.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnView.setText("View Deatil");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 492, -1, -1));

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 490, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compound", "Number", "Message", "Status", "Sender", "Receiver", "Result"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 720, 1320, 305));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Drug Manufactory 's Request ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, -1, -1));

        btnAssign.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnAssign.setText("Assign Me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1070, -1, -1));

        btnProcess.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 1060, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("Enterprise :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
          CreateCompoundJPanel panel=new CreateCompoundJPanel(userProcessContainer,compoundHistory);
        userProcessContainer.add("CreateProductJPanel", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         int selectedRow=jTable1.getSelectedRow();
         if (selectedRow<0) {
             JOptionPane.showMessageDialog(null,"Pelase select a row from table first to view details", "warning",JOptionPane.WARNING_MESSAGE);
         }else {
             Compound c=(Compound)jTable1.getValueAt(selectedRow, 0);
             ViewCompoundJPanel panel=new ViewCompoundJPanel(userProcessContainer, c);
              userProcessContainer.add("ViewDrugJPanel",panel);
               CardLayout layout=(CardLayout)userProcessContainer.getLayout();
              layout.next(userProcessContainer);
         }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow=jTable1.getSelectedRow();
        if (selectedRow>=0) {
            int dialogButton=JOptionPane.YES_NO_OPTION;
            int dialogResult=JOptionPane.showConfirmDialog(null, "would you want to delete the drug details?","Warning",dialogButton);
            if (dialogResult==JOptionPane.YES_NO_OPTION) {
                Compound c=(Compound)jTable1.getValueAt(selectedRow, 0);
                compoundHistory.deleteCompound(c);
                populateTable();
            }
        }else {
            JOptionPane.showMessageDialog(null,"Pelase select a row from table first", "warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable2.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        SendRequestToCompoundManufactory request = (SendRequestToCompoundManufactory)jTable2.getValueAt(selectedRow, 2);
     
        request.setStatus("Processing");
        
        ProcessCompoundJPanel processCompoundJPanel = new ProcessCompoundJPanel(userProcessContainer, request);
        userProcessContainer.add("processWorkRequestJPanel",  processCompoundJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable2.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        WorkRequest request = (WorkRequest)jTable2.getValueAt(selectedRow, 2);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateTable2();
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
