/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DrugManufactoryRole;

import Business.Compound.Compound;
import Business.Enterprise.Enterprise;
import Business.Organization.HealthFacility.DoctorOrganization;
import Business.Organization.Manufactory.CompoundManufactoryOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Verify.IntegerVerifier;
import Business.Verify.StringVerifier;
import Business.WorkQueue.DrugManufactory.SendRequestToCompoundManufactory;
import Business.WorkQueue.PatientRequest.RequestToDoctor;
import Interface.PatientRole.PatientWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhang
 */
public class RequestCompoundJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form RequestCompoundJPanel
     */
    public RequestCompoundJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueJLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valueJLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Enterprise :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 174, -1, -1));

        valueJLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        valueJLabel.setText("<Value>");
        add(valueJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 174, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Compound :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("Number :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 526, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("Message :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 735, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 337, 647, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 523, 647, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 732, 647, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 1007, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnSubmit.setText("Submit The Request");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 990, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         IntegerVerifier intVerify = new IntegerVerifier();
        StringVerifier stringVerify = new StringVerifier();
        
     if (intVerify.verify(jTextField2) && stringVerify.verify(jTextField1) && stringVerify.verify(jTextField3)) {   
        String compoundName=jTextField1.getText();
        String number=jTextField2.getText();
        String message=jTextField3.getText();
        
        Compound c=new Compound();
        c.setName(compoundName);
        
        
        SendRequestToCompoundManufactory request=new SendRequestToCompoundManufactory();
        request.setCompound(c);
        request.setCompoundNum(Integer.valueOf(number));
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CompoundManufactoryOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Has Send To Compound Manufactory Organization");
     }else {
        JOptionPane.showMessageDialog(null, "Wrong Input"); 
     }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DrugManufactoryWorkAreaJPanel dwjp = (DrugManufactoryWorkAreaJPanel) component;
        dwjp.populateTable2();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel valueJLabel;
    // End of variables declaration//GEN-END:variables
}
